### ISSUE TITLE
生成的dll咋没有导出函数

### ISSUE THREAD

**Issue by heheda123123** [bodong1987/AHeadLib.Net#1]
功能貌似不大对劲，aheadlib原版是指定dll，生成的代码会把函数调用转发到原来的dll
但是使用aheadlib.net生成的项目，编译出来的dll没有导出函数。

![image](https://github.com/user-attachments/assets/7b37a28f-6bf0-457b-8700-4e155437ae22)
而且看源码，好像只有内存patch的功能，并没有转发原来的函数

**Comment by bodong1987** [comment]
> 功能貌似不大对劲，aheadlib原版是指定dll，生成的代码会把函数调用转发到原来的dll 但是使用aheadlib.net生成的项目，编译出来的dll没有导出函数。
> 
> ![image](https://private-user-images.githubusercontent.com/97490782/348315961-7b37a28f-6bf0-457b-8700-4e155437ae22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTc5ODUsIm5iZiI6MTcyMTAxNzY4NSwicGF0aCI6Ii85NzQ5MDc4Mi8zNDgzMTU5NjEtN2IzN2EyOGYtNmJmMC00NTdiLTg3MDAtNGUxNTU0MzdhZTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA0MjgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZmRkNTU1NGY5NGJkN2ZiYTM0M2U1N2Q2NGIyZTIxOWI4Nzc3NjM2NWUxNTZmNjNiN2FkMjZhY2MzNDE3OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CfPQw9HLeKzrVkqAoWoKvrkJShKOg5DbpRb2D82dsK0) 而且看源码，好像只有内存patch的功能，并没有转发原来的函数

我这里生成了一个zlib的fake dll以及项目，你可以参考一下：
[zlib.zip](https://github.com/user-attachments/files/16230063/zlib.zip)
导出是通过asm代码结合#pragma linker来实现的。
![image](https://github.com/user-attachments/assets/0b524a1e-3cec-4a71-ba38-2a401cbfc5b1)
![image](https://github.com/user-attachments/assets/d6e5c533-e759-47d6-9655-163665ee065b)

另外建议直接从github下载目前的最新版v1.1.0.0

**Comment by heheda123123** [comment]
1 我是用的最新版，生成出来的项目的zlib.cpp里面确实没有这些导出的函数，dll是没问题的，你看看呢
[zip.zip](https://github.com/user-attachments/files/16230226/zip.zip)
我这里生成出来是这样的，就只有几十行代码
![image](https://github.com/user-attachments/assets/d234326e-f7f8-4eed-800a-77a24a49bf0c)

2 而且还有个问题，程序本身用起来不流畅，比如点击打开文件的按钮，或者点击生成，有时候会卡顿

**Comment by bodong1987** [comment]
> 1 我是用的最新版，生成出来的项目的zlib.cpp里面确实没有这些导出的函数，dll是没问题的，你看看呢 [zip.zip](https://github.com/user-attachments/files/16230226/zip.zip) 我这里生成出来是这样的，就只有几十行代码 ![image](https://private-user-images.githubusercontent.com/97490782/348604337-d234326e-f7f8-4eed-800a-77a24a49bf0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjM4MTgsIm5iZiI6MTcyMTAyMzUxOCwicGF0aCI6Ii85NzQ5MDc4Mi8zNDg2MDQzMzctZDIzNDMyNmUtZjdmOC00ZWVkLTgwMGEtNzdhMjRhNDliZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA2MDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NTA0MjMxM2ZkZTEzYWQxMDFiYWFjNGRkZjcyMGUxNTJiNmU5OTcyOWUyODRhMjQxOTkyNDgwNDE2NWY5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qJcY4b9Xoe18PW0QZFRVtCGrZWVBhheS0b3Q01c_rSI)
> 
> 2 而且还有个问题，程序本身用起来不流畅，比如点击打开文件的按钮，或者点击生成，有时候会卡顿

1,。我确实是重现了你说的问题。直接原因是从dll中读取到的导出函数列表是空的，这是DllExportInfo.cs中相关代码的bug。待我研究一下再回复你。感谢反馈。
2. 关于卡顿问题是因为DevExpress自带的文件选择对话框的问题，主要目的是为了保持程序风格的统一，既然你提到了，后面的版本我把它换成系统自带的，这样应该会好很多。不过在此之前，请允许我先看看DllExportInfo.cs的bug。

**Comment by bodong1987** [comment]
> 1 我是用的最新版，生成出来的项目的zlib.cpp里面确实没有这些导出的函数，dll是没问题的，你看看呢 [zip.zip](https://github.com/user-attachments/files/16230226/zip.zip) 我这里生成出来是这样的，就只有几十行代码 ![image](https://private-user-images.githubusercontent.com/97490782/348604337-d234326e-f7f8-4eed-800a-77a24a49bf0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjU0NTMsIm5iZiI6MTcyMTAyNTE1MywicGF0aCI6Ii85NzQ5MDc4Mi8zNDg2MDQzMzctZDIzNDMyNmUtZjdmOC00ZWVkLTgwMGEtNzdhMjRhNDliZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA2MzIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNTQzODc5NzI5MDNmZWNhYTFkZDY3OWFkZDZlODEwZjk2OWEyNjg4YWY1ZjJhZTQ4ZTA1ODg0NTI1MTdjNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nUVhyuiT5Fvl_lveiA51iKZELPzaUTKQvG1y9M-V270)
> 
> 2 而且还有个问题，程序本身用起来不流畅，比如点击打开文件的按钮，或者点击生成，有时候会卡顿

你好，感谢你的反馈。上面提到的两个问题已经处理完毕，你可以下载v1.2.0.0进行尝试，我本地对你提供的dll进行了测试，一切正常了。如有其它问题，欢迎反馈。
大家的反馈是我进步的源泉，感激不尽。
[v1.2.0.0](https://github.com/bodong1987/AHeadLib.Net/releases/tag/tags%2Fv1.2.0.0)


![image](https://github.com/user-attachments/assets/5db2a55a-bfc8-4ad2-a362-a3cdb3179787)
